source 'https://github.com/CocoaPods/Specs.git'

target 'iosApp' do
    use_frameworks!
    platform :ios, '15.3'
    pod 'composeApp', :path => '../composeApp'
    pod 'GoogleMaps', '9.0.0'

     post_install do |installer|
        installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.2"
          end
        end
      end
end